#[general]
#default_icon = "ğŸ“„"

[icons]
#firefox = "ğŸŒ"
firefox = "ï‰©"
Gnome-terminal = "ï„ "
#jetbrains-idea = "ğŸ“„"
jetbrains-idea = "ï„¡"

[options]
#no_names = true
remove_duplicates = true
no_icon_names = true
